XPos/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XPos.DataAccess;
using XPos.ViewModel;

namespace XPos.MVC.Controllers
{
    public class OrderController : Controller
    {
        // GET: Order
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SelectedProduct(long id)
        {
            ProductViewModel product = ProductRepo.ById(id);
            OrderDetailViewModel detail = new OrderDetailViewModel();
            detail.ProductId = product.Id;
            detail.ProductName = product.Name;
            detail.Price = product.Price;
            return PartialView("_SelectedProduct", detail);
        }

        [HttpPost]
        public ActionResult Payment(OrderHeaderViewModel model)
        {
            return PartialView("_Payment", model);
        }

        [HttpPost]
        public ActionResult Pay(OrderHeaderViewModel model)
        {
            ResultOrder result = OrderRepo.Post(model);
            return Json(
                new {
                    success = result.Success,
                    message = result.Message,
                    reference = result.Reference
                }, JsonRequestBehavior.AllowGet);
        }
    }
}

XPos/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XPos.DataAccess;
using XPos.ViewModel;

namespace XPos.MVC.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List(int page = 1, int cnt = 10)
        {
            var ListProduct = ProductRepo.All(page, cnt);
            decimal pgTotal = (decimal)ListProduct.Item2 / cnt;
            int fullPage = ListProduct.Item2 / cnt;
            if (pgTotal - fullPage > 0)
            {
                fullPage += 1;
            }
            ViewBag.PageTotal = fullPage;
            return PartialView("_List", ListProduct.Item1);
        }

        public ActionResult Create()
        {
            ViewBag.CategoryList = new SelectList(CategoryRepo.All(), "Id", "Name");
            ViewBag.VariantList = new SelectList(VariantRepo.ByCategory(0), "Id", "Name");
            return PartialView("_Create");
        }

        [HttpPost]
        public ActionResult Create(ProductViewModel model)
        {
            HttpPostedFileBase file = model.File;
            string[] fileName = file.FileName.Split('.');
            string newFile = DateTime.Now.ToString("yyyyMMddHHmmss") + "." + fileName[fileName.Length - 1];
            model.Image = newFile;
            ResponseResult result = ProductRepo.Update(model);
            if (result.Success)
            {
                if (file != null && file.ContentLength > 0)
                    try
                    {
                        string path = Path.Combine(Server.MapPath("~/FileUpload"),
                                                   Path.GetFileName(newFile));
                        file.SaveAs(path);
                    }
                    catch (Exception ex)
                    {
                        result.Success = false;
                        result.Message = ex.Message;
                    }
                else
                {
                    result.Success = false;
                    result.Message = "You have not specified a file.";
                }
            }
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Edit(long id)
        {
            ProductViewModel model = ProductRepo.ById(id);
            string fileName = "/FileUpload/no-image-icon-11.png";
            if (!String.IsNullOrEmpty(model.Image))
            {
                fileName = "/FileUpload/" + model.Image;
            }
            ViewBag.FileName = fileName;
            ViewBag.CategoryList = new SelectList(CategoryRepo.All(), "Id", "Name");
            ViewBag.VariantList = new SelectList(VariantRepo.ByCategory(model.CategoryId), "Id", "Name");
            return PartialView("_Edit", model);
        }

        [HttpPost]
        public ActionResult Edit(ProductViewModel model)
        {
            HttpPostedFileBase file = model.File;
            string[] fileName = file.FileName.Split('.');
            string newFile = DateTime.Now.ToString("yyyyMMddHHmmss") + "." + fileName[fileName.Length - 1];
            model.Image = newFile;
            ResponseResult result = ProductRepo.Update(model);
            if (result.Success)
            {
                if (file != null && file.ContentLength > 0)
                {
                    try
                    {
                        string path = Path.Combine(Server.MapPath("~/FileUpload"), Path.GetFileName(newFile));
                        file.SaveAs(path);
                    }
                    catch (Exception ex)
                    {
                        result.Success = false;
                        result.Message = ex.Message;
                    }
                }
                else
                {
                    result.Success = false;
                    result.Message = "You have not specified a file.";
                }
            }
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ProductList(string search = "")
        {
            var result = ProductRepo.ByFilter(search);
            return PartialView("_ProductList", result.Item1);
        }
    }
}

XPos/Controllers/VariantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XPos.DataAccess;
using XPos.ViewModel;

namespace XPos.MVC.Controllers
{
    public class VariantController : Controller
    {
        // GET: Variant
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {
            List<VariantViewModel> ListVariant = VariantRepo.All();
            return PartialView("_List", ListVariant);
        }

        public ActionResult ListByCategory(long id = 0)
        {
            //id => Category Id
            return PartialView("_ListByCategory", VariantRepo.ByCategory(id));
        }

        public ActionResult Create()
        {
            ViewBag.CategoryList = new SelectList(CategoryRepo.All(), "Id", "Name");
            return PartialView("_Create");
        }

        [HttpPost]
        public ActionResult Create(VariantViewModel model)
        {
            ResponseResult result = VariantRepo.Update(model);
            return Json(new {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Edit(long id)
        {
            ViewBag.CategoryList = new SelectList(CategoryRepo.All(), "Id", "Name");
            VariantViewModel model = VariantRepo.ById(id);
            return PartialView("_Edit", model);
        }

        [HttpPost]
        public ActionResult Edit(VariantViewModel model)
        {
            ResponseResult result = VariantRepo.Update(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Delete(long id)
        {
            ViewBag.CategoryList = new SelectList(CategoryRepo.All(), "Id", "Name");
            VariantViewModel model = VariantRepo.ById(id);
            return PartialView("_Delete", model);
        }

        [HttpPost]
        public ActionResult Delete(VariantViewModel model)
        {
            ResponseResult result = VariantRepo.Delete(model.Id);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

XPos/Views/Product/Index.cshtml
@{
    ViewBag.Title = "Product";
}

<h2>@ViewBag.Title</h2>

<div class="panel panel-primary">
    <div class="panel-heading">
        <input type="button" id="btn-create" value="Create New" class="btn btn-success" />
    </div>
    <div class="panel-body">
        Panel content
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Modal title</h4>
            </div>
            <div class="modal-body">
                ...
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            GetList(1);
        });

        var selPage = 1;
        var maxPage = 0;
        function GetList(page) {
            $.ajax({
                url: '@Url.Action("List","Product")',
                type: 'get',
                data: { page: page, cnt: 5 },
                success: function (result) {
                    $(".panel-body").html(result);
                    selPage = page;
                }
            });
        }

        $("#btn-create").click(function () {
            $.ajax({
                url: '@Url.Action("Create", "Product")',
                type: 'get',
                success: function (result) {
                    $(".modal-body").html(result);
                    $(".modal-title").html("Create New");
                    $(".modal").modal("show");
                }
            })
        });

        function MoveToPage(moveTo) {
            //console.log('moveTo: ' + moveTo + ', selPage: ' + selPage + ', maxPage: ' + maxPage);
            if (parseInt(selPage) + parseInt(moveTo) >= 1 && parseInt(selPage) + parseInt(moveTo) <= maxPage) {
                selPage = parseInt(selPage) + parseInt(moveTo);
                GetList(selPage);
            }
        }
    </script>
}

XPos/Views/Product/_Create.cshtml
@model XPos.ViewModel.ProductViewModel

@using (Html.BeginForm("Create", "Product", FormMethod.Post, new { id = "form-create", name = "form-create", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <a href="~/Views/Product/Index.cshtml">~/Views/Product/Index.cshtml</a>
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CategoryId, (IEnumerable<SelectListItem>)ViewBag.CategoryList, "Select Category", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.VariantId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.VariantId, (IEnumerable<SelectListItem>)ViewBag.VariantList, "Select Variant", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.VariantId, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
            <div class="form-horizontal">
                <div class="form-group">
                    @Html.LabelFor(model => model.Initial, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Initial, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Initial, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Stock, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Stock, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Stock, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.Active)
                            @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input id="File" name="File" type="file" onchange="readURL(this);"/>
                        <img src="/FileUpload/no-image-icon-11.png" id="img-canvas" alt="Sample" width="300px" />
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
}

@Scripts.Render("~/bundles/jqueryval")

<script type="text/javascript">
    $("#CategoryId").change(function () {
        $.ajax({
            url: '@Url.Action("ListByCategory", "Variant")',
            type: 'get',
            data: { id: $(this).val() },
            success: function (result) {
                $("#VariantId").html(result);
            }
        })
    });
    $("#form-create").submit(function () {
        var dataForm = new FormData($("#form-create")[0]);
        $.ajax({
            url: this.action,
            type: this.method,
            data: dataForm,
            cache: false,
            processData: false,
            contentType: false,
            success: function (result) {
                if (result.success) {
                    var entity = result.entity;
                    alert('Save successfull.\nInitial: ' + entity.Initial + '\nName: ' + entity.Name);
                    $(".modal").modal("hide");
                    GetList(selPage);
                } else {
                    alert('Error.\nMessage: ' + result.message)
                }
            }
        });
        return false;
    });

    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#img-canvas').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

XPos/Views/Product/_Edit.cshtml
@model XPos.ViewModel.ProductViewModel

@using (Html.BeginForm("Edit", "Product", FormMethod.Post, new { id = "form-edit", name = "form-edit", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CategoryId, (IEnumerable<SelectListItem>)ViewBag.CategoryList, "Select Category", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.VariantId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.VariantId, (IEnumerable<SelectListItem>)ViewBag.VariantList, "Select Variant", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.VariantId, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.Initial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Initial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Initial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Stock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Stock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Active)
                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input id="File" name="File" type="file" onchange="readURL(this);" />
                <img src="/FileUpload/no-image-icon-11.png" id="img-canvas" alt="Sample" width="300px" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@Scripts.Render("~/bundles/jqueryval")

<script type="text/javascript">
    $("#CategoryId").change(function () {
        $.ajax({
            url: '@Url.Action("ListByCategory", "Variant")',
            type: 'get',
            data: { id: $(this).val() },
            success: function (result) {
                $("#VariantId").html(result);
            }
        })
    });
    $("#form-edit").submit(function () {
        var dataForm = new FormData($("#form-edit")[0]);
        $.ajax({
            url: this.action,
            type: this.method,
            data: dataForm,
            cache: false,
            processData: false,
            contentType: false,
            success: function (result) {
                if (result.success) {
                    var entity = result.entity;
                    alert('Save successfull.\nInitial: ' + entity.Initial + '\nName: ' + entity.Name);
                    $(".modal").modal("hide");
                    GetList(selPage);
                } else {
                    alert('Error.\nMessage: ' + result.message)
                }
            }
        });
        return false;
    });

    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#img-canvas').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

XPos/Views/Product/_List.cshtml
@model IEnumerable<XPos.ViewModel.ProductViewModel>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CategoryName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VariantName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Initial)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Stock)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Active)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CategoryName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VariantName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Initial)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Stock)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Active)
                </td>
                <td>
                    <div class="btn-group btn-group-sm">
                        <button type="button" class="btn btn-warning btn-edit" data-id="@item.Id" title="Edit">
                            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                        </button>
                        <button type="button" class="btn btn-danger btn-delete" data-id="@item.Id" title="Delete">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        </button>
                    </div>
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <th colspan="9">
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        <li>
                            <a href="#" aria-label="Previous" onclick="MoveToPage(-1)">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        @{
                            for (int I = 0; I < ViewBag.PageTotal; I++)
                            {
                                <li><a href="#" class="btn-page">@(I + 1)</a></li>
                            }
                        }
                        <li>
                            <a href="#" aria-label="Next" onclick="MoveToPage(1)">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </th>
        </tr>
    </tfoot>
</table>

<script type="text/javascript">
    $(document).ready(function () {
        $(".pagination li").eq(selPage).addClass('active');
        maxPage = @ViewBag.PageTotal;
    });

    $(".btn-edit").click(function () {
        $.ajax({
            url: '@Url.Action("Edit", "Product")',
            type: 'get',
            data: { id: $(this).attr('data-id') },
            success: function (result) {
                $('.modal-body').html(result);
                $('.modal-title').html('Edit');
                $('.modal').modal('show');
            }
        });
    });

    $(".btn-delete").click(function () {
        $.ajax({
            url: '@Url.Action("Delete", "Product")',
            type: 'get',
            data: { id: $(this).attr('data-id') },
            success: function (result) {
                $('.modal-body').html(result);
                $('.modal-title').html('Delete');
                $('.modal').modal('show');
            }
        });
    });

    $(".btn-page").click(function () {
        selPage = $(this).html();
        $(".pagination li").eq(selPage).addClass('active');
        $(".pagination li").not(':eq(' + selPage + ')').removeClass('active');
        GetList(selPage);
    });
</script>

XPos/Views/Product/_ProductList.cshtml
@model IEnumerable<XPos.ViewModel.ProductViewModel>
<table class="table">
    <thead>
        <tr>
            <th>Select</th>
            <th>
                @Html.DisplayNameFor(model => model.Initial)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)/<br />
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Stock)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <button type="button" class="btn btn-success btn-select" data-dismiss="modal" data-id="@item.Id" title="Select">
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                    </button>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Initial)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)/<br />
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Stock)
                </td>
            </tr>
        }
    </tbody>
</table>

<script type="text/javascript">
    $(".btn-select").click(function () {
        $.ajax({
            url: '@Url.Action("SelectedProduct", "Order")',
            type: 'get',
            data: { id: $(this).attr("data-id") },
            success: function (result) {
                $("#order-table tbody").append(result);
                Summary();
            }
        })
    });
</script>