XPos/Controllers/CalcController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace XPos.MVC.Controllers
{
    public class CalcController : Controller
    {
        // GET: Calc
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Addition(long val1, long val2)
        {
            return Json(new
            {
                result = val1 + val2
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

XPos/Views/Calc/Index.cshtml
@{
    ViewBag.Title = "Calculator";
}

<h2>@ViewBag.Title</h2>
<table class="table table-bordered">
    <tr>
        <td>
            <input type="number" id="nil1" class="form-control" value="0"/>
        </td>
        <td>
            <input type="text" id="simbol" class="form-control" value="?" />
        </td>
        <td>
            <input type="number" id="nil2" class="form-control" value="0" />
        </td>
        <td>
            <input type="number" id="hasil" class="form-control" value="0" />
        </td>
    </tr>
    <tr>
        <td>
            <input type="button" id="btn-add" class="btn btn-success" value="0" />
        </td>
        <td>
            <input type="button" id="btn-subs" class="btn btn-warning" value="?" />
        </td>
        <td>
            <input type="button" id="btn-mul" class="btn btn-primary" value="0" />
        </td>
        <td>
            <input type="button" id="btn-div" class="btn btn-danger" value="0" />
        </td>
    </tr>
    
</table>

@section Scripts{
    <script type="text/javascript">
        $("#btn-add").click(function () {
            $.ajax({
                url: '@Url.Action("Addition", "Calc")',
                type: 'get',
                data: { val1: $("#nil1").val(), val2: $("#nil2").val() },
                success: function (result) {
                    $("#simbol").val("+");
                    $("#hasil").val(result.result);
                }
            });
        });
    </script>
}