XPos/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XPos.DataAccess;
using XPos.ViewModel;

namespace XPos.MVC.Controllers
{
    public class OrderController : Controller
    {
        // GET: Order
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SelectedProduct(long id)
        {
            ProductViewModel product = ProductRepo.ById(id);
            OrderDetailViewModel detail = new OrderDetailViewModel();
            detail.ProductId = product.Id;
            detail.ProductName = product.Name;
            detail.Price = product.Price;
            return PartialView("_SelectedProduct", detail);
        }

        [HttpPost]
        public ActionResult Payment(OrderHeaderViewModel model)
        {
            return PartialView("_Payment", model);
        }

        [HttpPost]
        public ActionResult Pay(OrderHeaderViewModel model)
        {
            ResultOrder result = OrderRepo.Post(model);
            return Json(
                new {
                    success = result.Success,
                    message = result.Message,
                    reference = result.Reference
                }, JsonRequestBehavior.AllowGet);
        }
    }
}

XPos/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XPos.DataAccess;
using XPos.ViewModel;

namespace XPos.MVC.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List(int page = 1, int cnt = 10)
        {
            var ListProduct = ProductRepo.All(page, cnt);
            decimal pgTotal = (decimal)ListProduct.Item2 / cnt;
            int fullPage = ListProduct.Item2 / cnt;
            if (pgTotal - fullPage > 0)
            {
                fullPage += 1;
            }
            ViewBag.PageTotal = fullPage;
            return PartialView("_List", ListProduct.Item1);
        }

        public ActionResult Create()
        {
            ViewBag.CategoryList = new SelectList(CategoryRepo.All(), "Id", "Name");
            ViewBag.VariantList = new SelectList(VariantRepo.ByCategory(0), "Id", "Name");
            return PartialView("_Create");
        }

        [HttpPost]
        public ActionResult Create(ProductViewModel model)
        {
            HttpPostedFileBase file = model.File;
            string[] fileName = file.FileName.Split('.');
            string newFile = DateTime.Now.ToString("yyyyMMddHHmmss") + "." + fileName[fileName.Length - 1];
            model.Image = newFile;
            ResponseResult result = ProductRepo.Update(model);
            if (result.Success)
            {
                if (file != null && file.ContentLength > 0)
                    try
                    {
                        string path = Path.Combine(Server.MapPath("~/FileUpload"),
                                                   Path.GetFileName(newFile));
                        file.SaveAs(path);
                    }
                    catch (Exception ex)
                    {
                        result.Success = false;
                        result.Message = ex.Message;
                    }
                else
                {
                    result.Success = false;
                    result.Message = "You have not specified a file.";
                }
            }
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Edit(long id)
        {
            ProductViewModel model = ProductRepo.ById(id);
            string fileName = "/FileUpload/no-image-icon-11.png";
            if (!String.IsNullOrEmpty(model.Image))
            {
                fileName = "/FileUpload/" + model.Image;
            }
            ViewBag.FileName = fileName;
            ViewBag.CategoryList = new SelectList(CategoryRepo.All(), "Id", "Name");
            ViewBag.VariantList = new SelectList(VariantRepo.ByCategory(model.CategoryId), "Id", "Name");
            return PartialView("_Edit", model);
        }

        [HttpPost]
        public ActionResult Edit(ProductViewModel model)
        {
            HttpPostedFileBase file = model.File;
            string[] fileName = file.FileName.Split('.');
            string newFile = DateTime.Now.ToString("yyyyMMddHHmmss") + "." + fileName[fileName.Length - 1];
            model.Image = newFile;
            ResponseResult result = ProductRepo.Update(model);
            if (result.Success)
            {
                if (file != null && file.ContentLength > 0)
                {
                    try
                    {
                        string path = Path.Combine(Server.MapPath("~/FileUpload"), Path.GetFileName(newFile));
                        file.SaveAs(path);
                    }
                    catch (Exception ex)
                    {
                        result.Success = false;
                        result.Message = ex.Message;
                    }
                }
                else
                {
                    result.Success = false;
                    result.Message = "You have not specified a file.";
                }
            }
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ProductList(string search = "")
        {
            var result = ProductRepo.ByFilter(search);
            return PartialView("_ProductList", result.Item1);
        }
    }
}

XPos/Views/Order/Index.cshtml
@{
    ViewBag.Title = "P.O.S";
}

<h2>@ViewBag.Title</h2>
<div class="panel panel-primary">
    <div class="panel-heading">
        <input type="button" id="btn-new-order" value="New Order" class="btn btn-success" />
        <input type="button" id="btn-payment" value="Payment" class="btn btn-primary" />
        <input type="button" id="btn-new-trans" value="New Trans" class="btn btn-danger" />

    </div>
    <div class="panel-body">
        <table class="table table-bordered" id="order-table">
            <thead>
                <tr>
                    <th style="width: 40%">Product Name</th>
                    <th style="width: 20%">Price</th>
                    <th style="width: 20%">Quantity</th>
                    <th style="width: 20%">Amount</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @*Order List ada disini*@
            </tbody>
            <tfoot>
                <tr>
                    <th colspan="2">
                        Total
                    </th>
                    <th>
                        <input type="number" id="tot-qty" value="0" name="tot-qty" class="form-control" />
                    </th>
                    <th>
                        <input type="number" id="tot-amount" value="0" name="tot-amount" class="form-control" />
                    </th>
                    <th>Action</th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Modal title</h4>
            </div>
            <div class="modal-body">
                ...
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        $("#btn-new-order").click(function () {
            $.ajax({
                url: '@Url.Action("ProductList", "Product")',
                type: 'get',
                success: function (result) {
                    $(".modal-body").html(result);
                    $(".modal-title").html("Select New Order");
                    $(".modal").modal("show");
                }
            })
        });

        function Remove(obj) {
            var tr = $(obj).closest('tr');
            var qty = tr.find("input[name=Quantity]").val();
            if (qty <= 0) {
                tr.remove();
            } else {
                var answer = confirm("Yakin mau dihapus?");
                if (answer) {
                    tr.remove();
                }
            }
        }

        function Calculate(obj) {
            var tr = $(obj).closest('tr');
            var prc = tr.find("input[name=Price]").val();
            var qty = tr.find("input[name=Quantity]").val();
            var amount = prc * qty;
            tr.find("input[name=Amount]").val(amount);
            Summary();
        }

        function Summary() {
            var qty = 0;
            var amount = 0;
            $("#order-table tbody").find("tr").each(function () {
                qty += parseFloat($(this).find("input[name=Quantity]").val());
                amount += parseFloat($(this).find("input[name=Amount]").val());
            })
            $("#tot-qty").val(qty);
            $("#tot-amount").val(amount);
        }

        var data = {};

        $("#btn-payment").click(function () {
            var details = [];
            $("#order-table tbody").find("tr").each(function () {
                var prodId = $(this).find("input[name=ProductId]").val();
                var prodName = $(this).find("input[name=ProductName]").val();
                var prc = $(this).find("input[name=Price]").val();
                var qty = $(this).find("input[name=Quantity]").val();
                var amount = $(this).find("input[name=Amount]").val();
                detail = {
                    ProductId: prodId,
                    ProductName: prodName,
                    Price: prc,
                    Quantity: qty,
                    Amount: amount
                };
                details.push(detail);
            });

            // Menampilkan data di console browser
            //console.log(details);

            data = {
                Quantity: $("#tot-qty").val(),
                Amount: $("#tot-amount").val(),
                Details: details
            }

            $.ajax({
                url: '@Url.Action("Payment", "Order")',
                type: 'post',
                data: { model: data },
                success: function (result) {
                    $(".modal-body").html(result);
                    $(".modal-title").html("Payment.");
                    $(".modal").modal("show");
                }
            })
        });
    </script>
}

XPos/Views/Order/_Payment.cshtml
@model XPos.ViewModel.OrderHeaderViewModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" id="form-payment">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Reference, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Reference, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Reference, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="Payment">Payment</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line" id="Payment" name="Payment" type="number" onkeyup="CalcPayment()" value="0.00">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="Change">Change</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line" id="Change" name="Change" type="number" readonly="readonly" value="@(Model.Amount * -1)">
            </div>
        </div>

        <table class="table">
            <thead>
                <tr>
                    <th>Prod. Name</th>
                    <th>Price</th>
                    <th>Qty</th>
                    <th>Amount</th>
                </tr>
            </thead>
            <tbody id="pay-order-list"></tbody>
        </table>

        <table class="table">
            <thead>
                <tr>
                    <th>Prod. Name</th>
                    <th>Price</th>
                    <th>Qty</th>
                    <th>Amount</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Details)
                {
                    <tr>
                        <td>@item.ProductName</td>
                        <td>@item.Price</td>
                        <td>@item.Quantity</td>
                        <td>@item.Amount</td>
                    </tr>
                }
            </tbody>
        </table>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" id="btn-cancel" value="Cancel" data-dismiss="modal" class="btn btn-default" />
                <input type="button" id="btn-pay" value="Pay!" class="btn btn-success" />
            </div>
        </div>
    </div>
}

@Scripts.Render("~/bundles/jqueryval")

<script type="text/javascript">
    $(document).ready(function () {
        //console.log(data.Details);
        data.Details.forEach(function (detail, idx) {
            var tr = "<tr>";
            tr += "<td>" + detail.ProductName + "</td>";
            tr += "<td>" + detail.Price + "</td>";
            tr += "<td>" + detail.Quantity + "</td>";
            tr += "<td>" + detail.Amount + "</td>";
            tr += "</tr>";
            $("#pay-order-list").append(tr);
        });
    });

    function CalcPayment() {
        var payment = $("#Payment").val();
        var amount = parseFloat(data.Amount);
        var change = parseFloat(payment) - parseFloat(amount);
        $("#Change").val(change);
    }

    $("#btn-pay").click(function () {
        $.ajax({
            url: '@Url.Action("Pay", "Order")',
            type: 'post',
            data: { model: data },
            success: function (result) {
                if (result.success) {
                    $(".modal-title").html("Payment. Thank you!");
                    $("#Reference").val(result.reference);
                    $("#Payment").attr("readonly", "readonly");
                    $("#btn-pay").remove();
                    $("#btn-cancel").val("Close!")
                    $("#btn-cancel").attr("onclick", "location.reload()");
                } else {
                    alert("Error:\n" + result.message);
                }
            }
        })
    });
</script>

XPos/Views/Order/_SelectedProduct.cshtml
@model XPos.ViewModel.OrderDetailViewModel
<tr>
    <td>
        @Html.HiddenFor(model => model.ProductId)
        @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
    </td>
    <td>
        @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
    </td>
    <td>
        @*@Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control", @type = "number" } })*@
        <input class="form-control text-box single-line" id="Quantity" name="Quantity" type="number" onchange="Calculate(this)" onkeyup="Calculate(this)" value="1">
    </td>
    <td>
        @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
    </td>
    <td>
        <button type="button" class="btn btn-danger btn-remove" onclick="Remove(this)" title="Remove">
            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
        </button>
    </td>
</tr>